### ISSUE TITLE
Style should be customizable

### ISSUE THREAD

**Issue by sapjax** [hax/atom-elastic-tabstops#4]
Your style set `box-shadow` to **hard-tab**:

``` css
box-shadow: inset -1px 0;
```

The `color` of `box-shadow` is inherit from `<atom-text-editor>`'s `color` which was setted by specifical theme.

In my atom editor it look like this:
￼![2 pic](https://cloud.githubusercontent.com/assets/990255/14069104/96118372-f4c7-11e5-9d55-943992fb8a67.jpg)
￼￼Then, I override the style of `elastic-tabstops.less`:

``` css
atom-text-editor::shadow {
    span.hard-tab {
         box-shadow : inset -1px 0;
         display    : inline-block;

         &:not(.indent-guide) {
            color: rgba(255, 255, 255, .3);
         }

        &.indent-guide:first-child {
             box-shadow : inset 1px 0, inset -1px 0;
        }
    }
}

```

It works well, but I think there should be a text-input for user to custom the `color` of `box-shadow`.
